name = "nabot-frontend"
main = ".output/server/index.mjs"
workers_dev = true
compatibility_date = "2024-07-12"

[site]
bucket = ".output/public"

[vars]
NUXT_PUBLIC_BACKEND_URL = "https://api-nabot.mori.space"

